server.port: 8080

spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false

# Defaults, overriden by environment variables with the same names
dvision.apiuser: dvisionuser
dvision.apipassword: dvisionpassword

multipart.maxFileSize: 5Mb

---
spring.profiles: local

---
spring.profiles: prod
